name: Build
on:
  push:
    branches:
      - main
    tags:
      - v*.*.*

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/tags/') != true }}

jobs:
  build_and_generate_apk:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clone repo
        if: startsWith(github.ref, 'refs/tags/') != true
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Extract tag name
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Generate APK
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG=${{ env.TAG_NAME }}
          NAME=$(echo $TAG | sed -e 's/^v//')
          CODE=$(git rev-list --count $TAG)

          echo "Version name: $NAME and Code: $CODE"
          
          ./gradlew :app:assembleDebug -Pversion_name=$NAME -Pversion_code=$CODE "-Dorg.gradle.jvmargs=-Xmx4g"

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@a74c6b72af54cfa997e81df42d94703d6313a2d0
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: |
            app/build/outputs/apk/debug/*.apk
